logging:
  level:
    org.zalando.logbook: TRACE
spring:
  sql:
    init:
      mode: ALWAYS
  datasource:
    url: jdbc:h2:file:./db/shareit
    driverClassName: org.h2.Driver
    username: sa
    password: password